source("functions/my_add_id.R")
# Remove col extra_informations and organize data frame
a_finite_forms = a_finite_forms[,-c(1,154:167)] %>% gather(value = "acceptability", key = "sentence", -id)
a_gerund_forms = a_gerund_forms[,-c(1,180:193)] %>% gather(value = "acceptability", key = "sentence", -id)
a_broken_forms = a_broken_forms[,-c(1,107:119)]  %>% gather(value = "acceptability", key = "sentence", -id)
a_past_participle_forms = a_past_participle_forms[,-c(1,154:166)]  %>% gather(value = "acceptability", key = "sentence", -id)
m_gerund_forms = m_gerund_forms[,-c(1,184:196)]  %>% gather(value = "acceptability", key = "sentence", -id)
m_indicative_forms = m_indicative_forms[,-c(1,170:183)]  %>% gather(value = "acceptability", key = "sentence", -id)
m_sem1_forms = m_sem1_forms[,-c(1,76:88)]  %>% gather(value = "acceptability", key = "sentence", -id)
m_sem2_forms = m_sem2_forms[,-c(1,83:95)] %>% gather(value = "acceptability", key = "sentence", -id)
m_past_participle_forms = m_past_participle_forms[,-c(1,164:176)] %>% gather(value = "acceptability", key = "sentence", -id)
