name: Deploy

on: [pull_request, workflow_dispatch]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT }}

      - name: Set up R
        uses: r-lib/actions/setup-r@v1

      - name: Push to shinyapps.io
        env:
          SHINYMANAGER_USER: ${{ secrets.SHINYMANAGER_USER }}
          SHINYMANAGER_PASSWORD: ${{ secrets.SHINYMANAGER_PASSWORD }}
        run: |
          rm .Rprofile  # shinyapps doesn't work with renv
          Rscript -e "rsconnect::setAccountInfo(name = ${{ secrets.SHINYAPPS_NAME }}, token = ${{ secrets.SHINYAPPS_TOKEN }}, secret = ${{ secrets.SHINYAPPS_SECRET }})"
          Rscript -e "rsconnect::deployApp()"
